//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonomium.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonomium.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sonomium に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_AppName {
            get {
                return ResourceManager.GetString("App_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Unspecified) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HTML_GenreUnspecfied {
            get {
                return ResourceManager.GetString("HTML_GenreUnspecfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ARTIST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Navigation_Artist {
            get {
                return ResourceManager.GetString("MainWindow_Navigation_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GENRE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Navigation_Genre {
            get {
                return ResourceManager.GetString("MainWindow_Navigation_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAIN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Navigation_Main {
            get {
                return ResourceManager.GetString("MainWindow_Navigation_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETTINGS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Navigation_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Navigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRACKS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Navigation_Tracks {
            get {
                return ResourceManager.GetString("MainWindow_Navigation_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play later に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageCurrent_PlayLater {
            get {
                return ResourceManager.GetString("PageCurrent_PlayLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageCurrent_PlayNow {
            get {
                return ResourceManager.GetString("PageCurrent_PlayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the album now played on the server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageCurrent_SelectNowPlayed {
            get {
                return ResourceManager.GetString("PageCurrent_SelectNowPlayed", resourceCulture);
            }
        }
    }
}
